
services:
  # PHP (Laravel) サービス
  app:
    container_name: techtinic-app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
      - storage-data:/var/www/html/storage
      - ./.ssh:/root/.ssh
      - ./docs:/var/www/html/docs
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    command: bash -c "mkdir -p /var/www/html/storage/logs /var/www/html/storage/framework/views && chown -R www-data:www-data /var/www/html/storage && php-fpm"

  # nginx サービス（HTTPS対応）
  web:
    container_name: techtinic-nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '${WEB_PORT}:443'
    volumes:
      - ./src:/var/www/html
      - storage-data:/var/www/html/storage
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app


  # PostgreSQL サービス
  db:
    container_name: techtinic-db
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '5433:5432'
    volumes:
      - techtinic-db-volume:/var/lib/postgresql/data

volumes:
  techtinic-db-volume:
  storage-data:
