FROM nginx:1.18-alpine

# タイムゾーン設定（必要なら）
ENV TZ=Asia/Tokyo

# 必要なパッケージをインストール（nss-tools, curl, openssl）
RUN apk add --no-cache nss-tools curl openssl

#証明書をコピーする。
COPY ./docker/nginx/ssl/server-cert.pem /etc/nginx/ssl/server-cert.pem
COPY ./docker/nginx/ssl/server-key.pem /etc/nginx/ssl/server-key.pem
RUN chmod 644 /etc/nginx/ssl/server-key.pem /etc/nginx/ssl/server-key.pem




# nginxの設定ファイルをコピー
COPY ./docker/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf

# 作業ディレクトリを指定
WORKDIR /var/www/html

# entrypoint.sh を削除したので、ENTRYPOINT を使用しないか、直接 nginx を起動
CMD ["nginx", "-g", "daemon off;"]